#=================================================
# Description: Build ubports using GitHub Actions
# Lisence: MIT
# Author: 0312birdzhang
# Credit: https://github.com/P3TERX/Actions-OpenWrt
#=================================================

name: Build System Image for Ubports

on: 
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt install debos bmap-tools android-sdk-libsparse-utils xz-utils f2fs-tools git

    - name: Downloading source code
      run: |
        git clone https://github.com/davidebangelista/msm8974-Mobian

    - name: Build HAL
      run: |
        cd msm8974-Mobian
        chmod +x build.sh
        bash -x build.sh
      shell: bash

    - name: Make zips
      run: |
        ls > log
        zip -r log.zip log

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MySecret }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload System-image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MySecret }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: log.zip
        asset_name: log.zip
        asset_content_type: application/zip
